version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: allu-shop-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: allu_shop
      MYSQL_USER: allu_user
      MYSQL_PASSWORD: allu_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - allu-shop-network
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: allu-shop-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - allu-shop-network
    command: redis-server --appendonly yes

  meilisearch:
    image: getmeili/meilisearch:v1.5
    container_name: allu-shop-meilisearch
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: secret_xyz
      MEILI_ENV: development
    ports:
      - "7700:7700"
    volumes:
      - meilisearch_data:/meili_data
    networks:
      - allu-shop-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  meilisearch_data:
    driver: local

networks:
  allu-shop-network:
    driver: bridge 